// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KillTheFly.Server.Migrations
{
    [DbContext(typeof(KTFDatabaseContext))]
    [Migration("20230704024435_FixingDatetimeCast")]
    partial class FixingDatetimeCast
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.5.23280.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KillTheFly.Shared.GameEntity", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("text");

                    b.Property<char>("Avatar")
                        .HasColumnType("character(1)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlayer")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAccess")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("KillTheFly.Shared.Kill", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VictimGuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("VictimGuid");

                    b.ToTable("Kills");
                });

            modelBuilder.Entity("KillTheFly.Shared.Movement", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("text");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int>("EndX")
                        .HasColumnType("integer");

                    b.Property<int>("EndY")
                        .HasColumnType("integer");

                    b.Property<string>("EntityGuid")
                        .HasColumnType("text");

                    b.Property<DateTime>("MoveDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("StartX")
                        .HasColumnType("integer");

                    b.Property<int>("StartY")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.HasIndex("EntityGuid");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("KillTheFly.Shared.Kill", b =>
                {
                    b.HasOne("KillTheFly.Shared.GameEntity", "Victim")
                        .WithMany()
                        .HasForeignKey("VictimGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Victim");
                });

            modelBuilder.Entity("KillTheFly.Shared.Movement", b =>
                {
                    b.HasOne("KillTheFly.Shared.GameEntity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityGuid");

                    b.Navigation("Entity");
                });
#pragma warning restore 612, 618
        }
    }
}
